name: HMLL Continuous Integration
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:

  integration-linux:
    name: Linux test-suite
    uses: ./.github/workflows/build.yml
    with:
      os: ubuntu-latest
      compiler-cc: gcc
      compiler-cxx: g++
      enable-rust: true
      enable-python: true
      enable-sanitizers: true
      # If this passes, the logic is likely fine everywhere

  integration-compat:
    name: Compat (${{ matrix.os }}, ${{ matrix.variant }})
    needs: [integration-linux] # Optional: Don't run if integration fails
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            variant: "MSVC"

          - os: macos-latest
            variant: "Clang"

          - os: ubuntu-latest
            variant: "Clang Static"
            cc: clang
            cxx: clang++
            static: true

          - os: ubuntu-24.04-arm
            variant: "ARM64"

    uses: ./.github/workflows/build.yml
    with:
      os: ${{ matrix.os }}
      compiler-cc: ${{ matrix.cc }}
      compiler-cxx: ${{ matrix.cxx }}
      static-build: ${{ matrix.static || false }}
      enable-rust: false
      enable-python: false

  cuda:
    name: CUDA Integration
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    uses: ./.github/workflows/build.yml
    with:
      os: ${{ matrix.os }}
      enable-cuda: true
      run-tests: false