name: Build hmll library

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, ubuntu-24.04-arm ]
        compiler: [
          { cc: gcc, cxx: g++ },
          { cc: clang, cxx: clang++ }
        ]
        static: [OFF, ON]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v6
      - name: Configure CMake
        env:
          CC: ${{ matrix.compiler.cc }}
          CXX: ${{ matrix.compiler.cxx }}
        run: cmake -B ${{ github.workspace }}/build \
          -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}  \
          -DHMLL_BUILD_STATIC=${{ matrix.static }}  \
          -DHMLL_BUILD_TESTS=ON                     \
          -DHMLL_ENABLE_SANITIZERS=ON

      - name: Build
        run:  cmake --build ${{ github.workspace }}/build --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{ github.workspace }}/build
        run: ctest -C ${{ env.BUILD_TYPE }}
