name: Build pyhmll library

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, ubuntu-24.04-arm ]
        compiler: [
          { cc: gcc, cxx: g++ },
          { cc: clang, cxx: clang++ }
        ]
        python: [ 3.12, 3.13, 3.13t ]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python }}
      - name: Configure CMake
        env:
          CC: ${{ matrix.compiler.cc }}
          CXX: ${{ matrix.compiler.cxx }}
        run: cmake -B ${{ github.workspace }}/build \
          -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}  \
          -DHMLL_ENABLE_PYTHON=ON                   \
          -DHMLL_BUILD_TESTS=ON                     \
          -DHMLL_ENABLE_SANITIZERS=ON

      - name: Build
        # Build your program with the given configuration
        run:  cmake --build ${{ github.workspace }}/build --config ${{env.BUILD_TYPE}}
